### ISSUE TITLE
Installing nethunter rootles problem

### ISSUE THREAD

**Issue by mmlive2010** [Hax4us/Hax4us.github.io#5]
I got that 
After installing 
$
![Screenshot_2020-04-22-11-25-22-603_com termux](https://user-images.githubusercontent.com/24499632/79965188-0147ec00-848c-11ea-8b9d-346b3b6a3ae4.jpg)
startkali
CANNOT LINK EXECUTABLE "proot": library "libtalloc.so.2" not found
$

**Comment by Hax4us** [comment]
Well It's not the place for this issue.
And do `apt update && apt upgrade` then problem should be solved
